# Generated by Django 4.0.4 on 2022-04-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_closed_post_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
    ]
